import styles from './AppIcon.module.scss';

const ICONS = {
  menu: 'menu',
  plus: 'add',
  search: 'search',
  bell: 'notifications',
  trash: 'delete',
  close: 'close',
  play: 'play_arrow',
  pause: 'pause',
  reset: 'replay',
  skip: 'skip_next',
  timer: 'timer',
  download: 'download',
  send: 'send',
  home: 'dashboard',
  book: 'school',
  task: 'assignment',
  code: 'code_blocks',
  note: 'sticky_note_2',
  chart: 'monitoring',
  spark: 'auto_awesome',
  settings: 'settings',
  moon: 'dark_mode',
  ai: 'smart_toy',
  analytics: 'analytics',
  trophy: 'military_tech',
  leaderboard: 'leaderboard',
  target: 'track_changes',
  insight: 'insights',
  route: 'route',
  lightbulb: 'lightbulb',
  pending: 'pending_actions',
  localFire: 'local_fire_department',
  star: 'kid_star',
  lock: 'lock',
  done: 'check_circle',
  clock: 'schedule',
  psychology: 'psychology',
  compare: 'compare_arrows',
  hub: 'hub',
  '🏠': 'dashboard',
  '📚': 'school',
  '📝': 'assignment',
  '💻': 'code_blocks',
  '⏱️': 'timer',
  '📊': 'monitoring',
  '🤖': 'smart_toy',
  '⚙️': 'settings',
  '✅': 'check_circle',
  '🏅': 'military_tech',
  '🎯': 'track_changes',
  '🏆': 'military_tech',
  '📈': 'insights',
  '🔥': 'local_fire_department',
  '⚡': 'bolt',
  '📖': 'book_2',
  '👑': 'workspace_premium',
  '💎': 'diamond',
  '💭': 'lightbulb',
  '🔗': 'hub',
  '🔍': 'search',
  '🧠': 'psychology',
  '💡': 'lightbulb',
  '🗺️': 'route',
  '🔔': 'notifications',
  '💾': 'download',
  '🎉': 'auto_awesome',
  '⚠️': 'warning',
  '🔒': 'lock',
  '⭐': 'kid_star',
};

export default function AppIcon({ name, size = 'md' }) {
  const iconName = ICONS[name];
  if (!iconName) return null;

  return (
    <span className={`${styles.icon} ${styles[size] || styles.md} material-symbols-rounded`} aria-hidden="true">
      {iconName}
    </span>
  );
}
